"""Add is_multiple_choice to Poll

Revision ID: fb97ff014d0d
Revises: 
Create Date: 2025-01-17 12:53:20.593400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb97ff014d0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multiple_choice', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_column('is_multiple_choice')

    # ### end Alembic commands ###
